
[versions]
micronaut = "5.0.0"
managed-eclipsestore="4.0.1"
firestore = '3.25.0'
micronaut-aws = "5.0.0-RC1"
micronaut-cache = "6.0.0"
micronaut-azure = "6.0.0-RC2"
micronaut-micrometer = "6.0.0"
micronaut-serde = "3.0.0"
micronaut-sql = "7.0.1"
micronaut-test-resources="4.0.0-M1"
micronaut-validation = "5.0.0"


[libraries]
micronaut-azure = { module = "io.micronaut.azure:micronaut-azure-bom", version.ref = "micronaut-azure" }
micronaut-aws = { module = "io.micronaut.aws:micronaut-aws-bom", version.ref = "micronaut-aws" }
micronaut-cache = { module = "io.micronaut.cache:micronaut-cache-bom", version.ref = "micronaut-cache" }
# Required to get dependabot updates for micronaut-core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

managed-eclipsestore-azure-storage = { module = 'org.eclipse.store:afs-azure-storage', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-google-firestore = { module = 'org.eclipse.store:afs-googlecloud-firestore', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-aws-s3 = { module = 'org.eclipse.store:afs-aws-s3', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-aws-dynamodb = { module = 'org.eclipse.store:afs-aws-dynamodb', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-cache = { module = 'org.eclipse.store:cache', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-sql = { module = 'org.eclipse.store:afs-sql', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-storage-embedded-configuration = { module = 'org.eclipse.store:storage-embedded-configuration', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-storage-restservice = { module = 'org.eclipse.store:storage-restservice', version.ref = 'managed-eclipsestore' }

eclipsestore-rest-gui = { module = 'org.eclipse.store:storage-restclient-app', version.ref = 'managed-eclipsestore' }
eclipsestore-persistence-binary-jdk8 = { module = 'org.eclipse.serializer:persistence-binary-jdk8', version.ref = 'managed-eclipsestore' }

testcontainers = { module = "org.testcontainers:testcontainers" }
testcontainers-minio = { module = "org.testcontainers:testcontainers-minio" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
jupiter-jupiter-params = { module = 'org.junit.jupiter:junit-jupiter-params' }
jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api' }
junit-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine' }

azuresdk-blob = { module = 'com.azure:azure-storage-blob'}
firestore-sdk = { module = 'com.google.cloud:google-cloud-firestore', version.ref = 'firestore' }
awssdk-s3 = { module = 'software.amazon.awssdk:s3' }
awssdk-dynamodb = { module = 'software.amazon.awssdk:dynamodb' }
