[versions]
micronaut-docs = "2.0.0"
micronaut = "4.5.4"
groovy = "4.0.17"
kotlin = '1.9.24'
spock = "2.3-groovy-4.0"
managed-eclipsestore='1.4.0'
azure-blob = '12.26.1'

micronaut-aws = "4.6.0"
micronaut-cache = "4.3.0"
micronaut-logging = "1.3.0"
micronaut-micrometer = "5.7.1"
micronaut-serde = "2.10.2"
micronaut-sql = "5.7.0"
micronaut-test = "4.4.0"
micronaut-test-resources="2.5.2"
micronaut-validation = "4.6.1"

[libraries]
micronaut-aws = { module = "io.micronaut.aws:micronaut-aws-bom", version.ref = "micronaut-aws" }
micronaut-cache = { module = "io.micronaut.cache:micronaut-cache-bom", version.ref = "micronaut-cache" }
# Required to get dependabot updates for micronaut-core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }
micronaut-test-resources = { module = "io.micronaut.testresources:micronaut-test-resources-bom", version.ref = "micronaut-test-resources" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

managed-eclipsestore-azure-storage = { module = 'org.eclipse.store:afs-azure-storage', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-aws-s3 = { module = 'org.eclipse.store:afs-aws-s3', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-aws-dynamodb = { module = 'org.eclipse.store:afs-aws-dynamodb', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-cache = { module = 'org.eclipse.store:cache', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-sql = { module = 'org.eclipse.store:afs-sql', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-storage-embedded-configuration = { module = 'org.eclipse.store:storage-embedded-configuration', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-storage-restservice = { module = 'org.eclipse.store:storage-restservice', version.ref = 'managed-eclipsestore' }

eclipsestore-rest-gui = { module = 'org.eclipse.store:storage-restclient-app', version.ref = 'managed-eclipsestore' }
eclipsestore-persistence-binary-jdk8 = { module = 'org.eclipse.serializer:persistence-binary-jdk8', version.ref = 'managed-eclipsestore' }
eclipsestore-persistence-binary-jdk17 = { module = 'org.eclipse.serializer:persistence-binary-jdk17', version.ref = 'managed-eclipsestore' }

testcontainers = { module = "org.testcontainers:testcontainers" }
testcontainers-minio = { module = "org.testcontainers:minio" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter" }
jupiter-jupiter-params = { module = 'org.junit.jupiter:junit-jupiter-params' }
jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api' }
junit-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine' }
kotlin-stdlib = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk8', version.ref = 'kotlin' }

azuresdk-blob = { module = 'com.azure:azure-storage-blob', version.ref = "azure-blob"}
awssdk-s3 = { module = 'software.amazon.awssdk:s3' }
awssdk-dynamodb = { module = 'software.amazon.awssdk:dynamodb' }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
