Configuration of an https://docs.eclipsestore.io/manual/storage/storage-targets/blob-stores/azure-storage.html requires a bean of type `BlobServiceClient` and configuration.

To get started, add the following dependencies:

dependency:azure-storage-blob[groupId=com.azure,scope=runtime]

The configuration can then be defined as follows:

[configuration]
----
eclipsestore:
    blob:
        storage:
            default:                               # <1>
                container-name: eclipsestore          # <2>
                root-class: com.example.model.Root # <3>
----
<1> The name for the created Storage Manager
<2> The name of the Azure container to use for storage
<3> The root class of the object graph to store

The storage manager will first attempt to look up an BlobServiceClient with the same name as the Storage Manager, and if this is not found, it will attempt to look up an un-named BlobServiceClient bean.

If you require to use an BlobServiceClient with a different name, this can be configured via the `blob-service-client-name` property as below.

[configuration]
----
eclipsestore:
    blob:
        storage:
            default:
                blob-client-name: my-s3-client       # <1>
                container-name: eclipsestore
                root-class: com.example.model.Root
----
<1> The name of the BlobServiceClient bean to use
